<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-HAB3M0C" ignored="0" name="Test" tests="3" failures="1" timestamp="2022-08-17T18:07:25 IST" time="44.561" errors="0">
  <testcase name="invalidPassword" time="6.484" classname="com.qa.tests.LoginTests">
    <failure type="java.lang.AssertionError" message="expected [Username and password do not match any user in this service.] but found [Username and password do not match any user in this service.txt]">
      <![CDATA[java.lang.AssertionError: expected [Username and password do not match any user in this service.] but found [Username and password do not match any user in this service.txt]
at com.qa.tests.LoginTests.invalidPassword(LoginTests.java:95)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- invalidPassword -->
  <testcase name="invalidUsername" time="2.764" classname="com.qa.tests.LoginTests"/>
  <testcase name="successfulLogin" time="4.077" classname="com.qa.tests.LoginTests"/>
</testsuite> <!-- Test -->
